### ISSUE TITLE
support for a `$.attr()` like function

### ISSUE THREAD

**Issue by jbernsie** [rikulo/dquery#7]
just wondering if there is a plan in place to add support for manipulating element attributes simmilar to `$.attr()`

**Comment by blakemcbride** [comment]
Little scary.  No answer in over a year...

**Comment by tomyeh** [comment]
Sorry for late response. It is not in our plan. We're short of resources to make it as complete as JQuery. We now focus more on stability and support of Bootjack.

Of course, your pull requests are always welcome:)
